MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  ID_LOSS_MARGIN : 0.3
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0
  I2T_WEIGHT: 1.0
  T2I_WEIGHT: 1.0
  VIFI_WEIGHT: 'vifi_weight.pth'
  USE_VIFI_WEIGHT : True
  PROMPT_LEN : 8
  USE_LEARNABLE_PROMPT : True
  PBP_CAMERA: False
  USE_ADAPTER: True
  ADAPTER_TYPE: 'v1'
  ALPHA: 3
  BYTA: 3

  USE_PART_MODEL: True
  USE_PART_QUERY_CROSS_FRAME_ATTN: True
  USE_TEMPORAL_WEIGHT: True

  TRI_PART_LOSS_WEIGHT: 1.0
  ID_LOSS_PARTS_WEIGHT: 0.25
  PART_ALIGN_LOSS_WEIGHT: 0.
  CROSS_PLATFORM_ALIGN_LOSS_WEIGHT: 0.
  NUM_PART_LAYER: 1
  NUM_PART: 4

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SEQ_LEN: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 10
    WARMUP_EPOCHS: 5

  STAGE2:
    IMS_PER_BATCH: 32
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.0002
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.00025
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 80
    CHECKPOINT_PERIOD: 80
    LOG_PERIOD: 50
    EVAL_PERIOD: 10
    BIAS_LR_FACTOR: 2

    STEPS: [40, 60]
    GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 16
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  ALL_FRAMES: False
  DISTANCE: 'cosine'

DATASETS:
  NAMES: ('lsvid')
  ROOT_DIR: ('/home/Newdisk1/luowenlong/Datasets/LS-VID')
OUTPUT_DIR: './output/ls-vid'